### ISSUE TITLE
non-asciss characters in tracker description

### ISSUE THREAD

**Issue by voko** [voko/python-teamforge#2]
coming from downstream cyloncloner, issue [#6](/voko/teamforge-cyloncloner/issues/6).

Log:

```
TrackerApp->getTrackerData
 Traceback (most recent call last):, referer: https://teamforge.server/sf/go/artf563537?nav=1&_pagenum=1&returnUrlKey=1477063854655
   File "/var/www/cgi-bin/cyloncloner/cyloncloner.cgi", line 964, in <module>, referer: https://teamforge.server/sf/go/artf563537?nav=1&_pagenum=1&returnUrlKey=1477063854655
     , referer: https://teamforge.server/sf/go/artf563537?nav=1&_pagenum=1&returnUrlKey=1477063854655
 sys.exit(myApplication.main()), referer: https://teamforge.server/sf/go/artf563537?nav=1&_pagenum=1&returnUrlKey=1477063854655
   File "/var/www/cgi-bin/cyloncloner/cyloncloner.cgi", line 951, in main, referer: https://teamforge.server/sf/go/artf563537?nav=1&_pagenum=1&returnUrlKey=1477063854655
     , referer: https://teamforge.server/sf/go/artf563537?nav=1&_pagenum=1&returnUrlKey=1477063854655
 self.clone(), referer: https://teamforge.server/sf/go/artf563537?nav=1&_pagenum=1&returnUrlKey=1477063854655
   File "/var/www/cgi-bin/cyloncloner/cyloncloner.cgi", line 759, in clone, referer: https://teamforge.server/sf/go/artf563537?nav=1&_pagenum=1&returnUrlKey=1477063854655
     , referer: https://teamforge.server/sf/go/artf563537?nav=1&_pagenum=1&returnUrlKey=1477063854655
 self.trace('\\n%s' % newartifact.report('Cloned Artifact Summary')), referer: https://teamforge.server/sf/go/artf563537?nav=1&_pagenum=1&returnUrlKey=1477063854655
   File "/var/www/cgi-bin/cyloncloner/cyloncloner.cgi", line 165, in report, referer: https://teamforge.server/sf/go/artf563537?nav=1&_pagenum=1&returnUrlKey=1477063854655
     , referer: https://teamforge.server/sf/go/artf563537?nav=1&_pagenum=1&returnUrlKey=1477063854655
 value = str(val), referer: https://teamforge.server/sf/go/artf563537?nav=1&_pagenum=1&returnUrlKey=1477063854655
 UnicodeEncodeError, referer: https://teamforge.server/sf/go/artf563537?nav=1&_pagenum=1&returnUrlKey=1477063854655
 : , referer: https://teamforge.server/sf/go/artf563537?nav=1&_pagenum=1&returnUrlKey=1477063854655
 'ascii' codec can't encode character u'\\u2013' in position 165: ordinal not in range(128), referer: https://teamforge.server/sf/go/artf563537?nav=1&_pagenum=1&returnUrlKey=1477063854655
 , referer: https://teamforge.server/sf/go/artf563537?nav=1&_pagenum=1&returnUrlKey=1477063854655
 Premature end of script headers: cyloncloner.cgi, referer: https://teamforge.server/sf/go/artf563537?nav=1&_pagenum=1&returnUrlKey=1477063854655
```

**Comment by voko** [comment]
was not an API issue, but rather utf-unsafe code in cyloncloner. Closing this one.
